<?xml version="1.0" encoding="utf-8"?>

<!--
  Description of the ROSBOT3 robot.
  Autor original: Helio Perroni Filho
  Adaptado por: Vito Rodrigues Franzosi
  Date: 06.11.2025
-->

<robot name="rosbot3" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find rosbot3_description)/urdf/ugv02.xacro"/>

  <xacro:property name="payload_base_length" value="${10.0 * M}"/>
  <xacro:property name="payload_base_width" value="${10.0 * M}"/>
  <xacro:property name="payload_base_height" value="${94.0 * M}"/>

  <xacro:property name="lidar_size_x" value="${20.0 * M}"/>  <!-- comprimento -->
  <xacro:property name="lidar_size_y" value="${80.0 * M}"/>   <!-- largura -->
  <xacro:property name="lidar_size_z" value="${20.0 * M}"/>   <!-- altura -->
  
  <xacro:solid_block
    name="payload_base"
    size_x="${payload_base_length}"
    size_y="${payload_base_width}"
    size_z="${payload_base_height}"
  />

  <xacro:joint_fixed
    parent="fenders_top"
    child="payload_base"
    x="${-50.0 * M}"
  />

  <xacro:camera_link name="camera_front"/>
  <xacro:joint_fixed
    parent="fenders_top"
    child="camera_front"
  />

  <xacro:solid_block
    name="lidar"
    size_x="${lidar_size_x}"
    size_y="${lidar_size_y}"
    size_z="${lidar_size_z}"
  />

  <xacro:joint_fixed
    parent="payload_base"
    child="lidar"
    z="${payload_base_height * 0.5 + lidar_size_z * 0.5}"
  />

  <link name="laser"/>
  <xacro:joint_fixed
    parent="lidar"
    child="laser"
    z="${0.5 * lidar_size_z}"
  />
</robot>