<?xml version="1.0" encoding="utf-8"?>

<!--
  Description of the ROSBOT3 robot.
  Author: Vito Rodrigues Franzosi
  Date: 06.11.2025
-->

<robot name="rosbot3" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find rosbot3_description)/urdf/ugv02.xacro"/>

  <xacro:property name="payload_base_length" value="${200.0 * M}"/> <!-- comprimento da base para sensores -->
  <xacro:property name="payload_base_width" value="${223.0 * M}"/> <!-- largura da base para sensores -->
  <xacro:property name="payload_base_height" value="${1.0 * M}"/> <!-- altura da base para sensores -->

  <xacro:property name="lidar_radius" value="${10.0 * M}"/> <!-- raio do cilindro do LiDAR -->
  <xacro:property name="lidar_height" value="${38.0 * M}"/> <!-- altura do LiDAR -->

  <!-- Corpo principal do robÃ´ -->
  <xacro:solid_block_red
    name="payload_base"
    size_x="${payload_base_length}"
    size_y="${payload_base_width}"
    size_z="${payload_base_height}"
  />

<!-- Junta fixa conectando a base de carga ao corpo principal -->
  <xacro:joint_fixed
    parent="body"
    child="payload_base"
    z="${0.5 * (body_height + payload_base_height)}"
  />

  <xacro:camera_link name="camera_front"/>
  <xacro:joint_fixed
    parent="payload_base"
    child="camera_front"
    x="${0.5 * payload_base_length}"
  />

  <xacro:solid_block_black
    name="lidar"
    size_x="${lidar_radius}"
    size_y="${lidar_radius}"
    size_z="${lidar_height}"
  />

  <xacro:joint_fixed
    parent="payload_base"
    child="lidar"
    x="${0.5 * payload_base_height}"
    z="${0.5 * (payload_base_height + lidar_height)}"
  />

  <link name="laser"/>
  <xacro:joint_fixed
    parent="lidar"
    child="laser"
    z="${0.5 * lidar_height}"
  />
</robot>
