<?xml version="1.0" encoding="utf-8"?>

<!--
  Description of the Waveshare UGV02 mobile base upon which ROSBOT3 is built.
  Author: Helio Perroni Filho
  Adapted by: Vito Rodrigues Franzosi
  Date: 06.11.2025
-->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find ros_commons)/urdf/domain.xacro"/>

  <xacro:property name="M" value="0.001"/>

  <xacro:property name="ground_clearance" value="${23.0 * M}"/> <!-- Distância do solo até a parte mais baixa do corpo -->
  <xacro:property name="overall_height" value="${141.0 * M}"/> <!-- Altura total do robô -->

  <xacro:property name="fender_height" value="${10.0 * M}"/>

  <xacro:property name="wheel_separation" value="${149.0 * M}"/> <!-- Distância entre as rodas esquerda e direita -->
  <xacro:property name="wheel_diameter" value="${84.0 * M}"/> <!-- Diâmetro da roda -->
  <xacro:property name="wheelbase" value="${200.0 * M - wheel_diameter}"/> <!-- Distância entre os eixos dianteiro e traseiro -->
  <xacro:property name="wheel_radius" value="${0.5 * wheel_diameter}"/> <!-- Raio da roda -->
  <xacro:property name="wheel_thickness" value="${50.0 * M}"/>  <!-- Espessura da roda -->

  <xacro:property name="fender_length" value="${233.0 * M}"/> <!-- Comprimento dos para-lamas -->
  <xacro:property name="fender_thickness" value="${3.0 * M}"/>  <!-- Espessura dos para-lamas -->
  <xacro:property name="fender_top_gap" value="${1.0 * M}"/>  <!-- Espaço entre o topo do para-lama e o corpo -->
  <xacro:property name="fender_side_gap" value="${5.0 * M}"/> <!-- Espaço entre o lado do para-lama e a roda -->

  <xacro:property name="body_length" value="${200.0 * M}"/> <!-- Comprimento do corpo -->
  <xacro:property name="body_width" value="${149.0 * M}"/>  <!-- Largura do corpo -->
  <xacro:property name="body_height" value="${80.0 * M}"/> <!-- Altura do corpo -->

  <xacro:property name="fender_top_width" value="${body_width + 2.0 * (wheel_thickness + fender_side_gap)}"/> <!-- Largura do topo do para-lama -->
  <xacro:property name="fender_side_width" value="${wheel_radius + fender_thickness + fender_top_gap}"/> <!-- Largura do lado do para-lama -->

  <xacro:property name="fender_side_y_offset" value="${0.5 * (fender_top_width + fender_thickness)}"/> <!-- Deslocamento Y do lado do para-lama -->
  <xacro:property name="fender_side_z_offset" value="${0.5 * (fender_thickness - fender_side_width)}"/> <!-- Deslocamento Z do lado do para-lama -->

  <xacro:property name="wheel_axle_z_offset" value="${wheel_radius - 0.5 * body_height - ground_clearance}"/> <!-- Deslocamento Z do eixo da roda -->  

  <xacro:macro
    name="wheels"
    params="position"
  >
    <xacro:solid_cylinder
      name="wheel_${position}_left"
      length="${wheel_thickness}"
      radius="${wheel_radius}"
      roll="${90.0 * DEG}"
      material="Black"
    />

    <xacro:solid_cylinder
      name="wheel_${position}_right"
      length="${wheel_thickness}"
      radius="${wheel_radius}"
      roll="${90.0 * DEG}"
      material="Black"
    />

    <xacro:solid_cylinder
      name="wheel_${position}_axle"
      length="${wheel_separation}"
      radius="0.005"
      roll="${90.0 * DEG}"
    />

    <xacro:joint_continuous
      name="joint_wheel_${position}_left"
      parent="wheel_${position}_axle"
      child="wheel_${position}_left"
      y="${(wheel_separation + wheel_thickness) * 0.5}"
      axis="0 1 0"
    />

    <xacro:joint_continuous
      name="joint_wheel_${position}_right"
      parent="wheel_${position}_axle"
      child="wheel_${position}_right"
      y="${(wheel_separation + wheel_thickness) * -0.5}"
      axis="0 1 0"
    />
  </xacro:macro>

  <xacro:wheels position="front"/>
  <xacro:wheels position="rear"/>

  <xacro:solid_block
    name="body"
    size_x="${body_length}"
    size_y="${body_width}"
    size_z="${body_height}"
  />

  <xacro:solid_block
    name="fenders_top"
    size_x="${fender_length}"
    size_y="${fender_top_width}"
    size_z="${fender_thickness}"
    material="Red"
  />

  <xacro:joint_fixed
    parent="body"
    child="fenders_top"
    z="${0.5 * (body_height + fender_thickness)}"
  />

  <xacro:joint_fixed
    parent="body"
    child="wheel_front_axle"
    x="${0.5 * wheelbase}"
    z="${wheel_axle_z_offset}"
  />

  <xacro:joint_fixed
    parent="body"
    child="wheel_rear_axle"
    x="${-0.5 * wheelbase}"
    z="${wheel_axle_z_offset}"
  />

  <link name="base_link"/>
  <xacro:joint_fixed
    parent="base_link"
    child="body"
    z="${ground_clearance + 0.5 * body_height}"
  />
</robot>
